<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DemoPaymentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PayHereController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/shop', [ProductController::class, 'index'])->name('shop');
Route::get('/product/{product:slug}', [ProductController::class, 'show'])->name('product.show');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}/confirmation', [OrderController::class, 'confirmation'])->name('orders.confirmation');

    // Demo payment gateway (active while awaiting PayHere merchant approval)
    Route::get('/demo-payment/{order}', [DemoPaymentController::class, 'checkout'])->name('demo-payment.checkout');
    Route::post('/demo-payment/{order}/pay', [DemoPaymentController::class, 'pay'])->name('demo-payment.pay');

    // PayHere hosted checkout — browser-facing routes (user must be logged in)
    Route::get('/payhere/{order}/checkout', [PayHereController::class, 'checkout'])->name('payhere.checkout');
    Route::get('/payhere/return', [PayHereController::class, 'return'])->name('payhere.return');
    Route::get('/payhere/cancel', [PayHereController::class, 'cancel'])->name('payhere.cancel');
});

// PayHere server-to-server webhook — public, no auth, no CSRF (PayHere's server calls this)
Route::post('/payhere/notify', [PayHereController::class, 'notify'])
    ->name('payhere.notify')
    ->withoutMiddleware([VerifyCsrfToken::class]);

Route::prefix('admin')->middleware(['auth', 'can:access-admin'])->name('admin.')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::resource('products', AdminProductController::class);
});

require __DIR__.'/auth.php'; // generated by Breeze — keep this line if it already exists
